title: 'Quality of video '
description: 'Quality of the products will be delivered on high quality platforms '
template:
  repo: quality-of-video-template
  name: quality-of-video
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
